---
# directories
output_dir:  results/ # should be kept
working_dir: temp_dir/    # can be removed (temporary files)

# Binaries
fastp_binary: /data/Programs/fastp/fastp
minimap2_binary: /data/Programs/minimap2/minimap2
multiqc_binary: /home/sivasubramani/.local/bin/multiqc
samtools_binary: /data/Programs/samtools-1.9/samtools
bcftools_binary: /data/Programs/bcftools-1.9/bcftools


# samples to condition
units: samples.tsv

# refs 
genome_fasta: "/ngs/Misc/COV/Snakemake/Ca.fa"

# read quality trimming
fastp:
  qualified_quality_phred: 30 # Phred+33 score (> 15 for Proton Ion, > 30 or more for Illumina) 
  adaptor_fasta: "/data/Programs/Trimmomatic-0.39/adapters/TruSeq3-PE.fa"

