---
# directories
output_dir:  results/ # should be kept
working_dir: temp_dir/ # can be removed (temporary files)

# Binaries - Make sure the below mentioned tools are installed in the system. The reason we are not using wrappers for these rules, because, we are pipeling the outputs to reduce run times.
fastp_binary: fastp
minimap2_binary: minimap2
samtools_binary: samtools
bcftools_binary: bcftools


# samples to condition; Tab delimited file; sample<TAB>fq1<TAB>fq2
units: "config/samples.tsv"

# refs 
genome_fasta: "test-data/NC_045512.fasta"

# read quality trimming
fastp:
  qualified_quality_phred: 30 # Phred+33 score (> 15 for Proton Ion, > 30 or more for Illumina) 
  adaptor_fasta: "extras/TruSeq3-PE.fa"

